-- Insight events: actionable insights generated by the insight engine
CREATE TABLE insight_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  scenario_id TEXT NOT NULL,
  category TEXT NOT NULL,
  severity TEXT NOT NULL,
  detection JSONB NOT NULL,
  cause JSONB NOT NULL,
  solution JSONB NOT NULL,
  action JSONB,
  status TEXT NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '7 days',
  acted_at TIMESTAMPTZ,

  CONSTRAINT valid_severity CHECK (severity IN ('critical', 'warning', 'info', 'opportunity')),
  CONSTRAINT valid_status CHECK (status IN ('new', 'seen', 'acted', 'dismissed', 'expired'))
);

CREATE INDEX idx_insight_business ON insight_events(business_id, status, created_at DESC);
CREATE INDEX idx_insight_scenario ON insight_events(scenario_id, created_at DESC);

-- Prevent duplicate active insights for same scenario per business
CREATE UNIQUE INDEX idx_insight_active
  ON insight_events(business_id, scenario_id)
  WHERE status IN ('new', 'seen');

-- Action results: tracks what happened after user acted on an insight
CREATE TABLE action_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  insight_event_id UUID NOT NULL REFERENCES insight_events(id) ON DELETE CASCADE,
  business_id UUID NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL,
  executed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  result_data JSONB,
  measured_effect JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_action_results_business ON action_results(business_id, created_at DESC);

-- RLS
ALTER TABLE insight_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE action_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own insights" ON insight_events
  FOR SELECT USING (
    business_id IN (SELECT id FROM businesses WHERE user_id = auth.uid())
  );

CREATE POLICY "Users can update own insight status" ON insight_events
  FOR UPDATE USING (
    business_id IN (SELECT id FROM businesses WHERE user_id = auth.uid())
  );

CREATE POLICY "System can insert insights" ON insight_events
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can view own action results" ON action_results
  FOR SELECT USING (
    business_id IN (SELECT id FROM businesses WHERE user_id = auth.uid())
  );

CREATE POLICY "System can insert action results" ON action_results
  FOR INSERT WITH CHECK (true);
